blank_issues_enabled: true

contact_links:
  - name: ğŸ—¨ï¸ Discussions
    url: https://github.com/dotnetcore/BootstrapBlazor/discussions
    about: Please post any questions during use here
  - name: ğŸš€ Quick start
    url: https://github.com/dotnetcore/BootstrapBlazor/discussions/categories/quick-start
    about: About BootstrapBlazor quick start please visit here
