name: Deploy To Huawei VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Sync Huawei Clound VM
        uses: appleboy/ssh-action@master
        env:
          BRANCH_NAME: ${{ env.GITHUB_REF }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd ~/BootstrapBlazor
            git checkout dev
            sh ~/deploy-blazor.sh
            sh ~/deploy-wasm.sh
