name: Package to Nuget

on:
  push:
    branches:
      - pack
      - hotfix

jobs:
  pack:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.400

    - name: Publish to Nuget
      env: 
        NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}
      run: |
        dotnet pack src/BootstrapBlazor -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate
