name: Package Extensions to Nuget

on:
  push:
    branches:
      - release

jobs:
  pack:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x

    - name: Setup .NET Core 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Publish to Nuget
      env: 
        NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}
        Bundle: True
      run: |      
        dotnet pack src/Extensions/Components/BootstrapBlazor.Chart -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.Chart.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate
        
        dotnet pack src/Extensions/Components/BootstrapBlazor.TableExport -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.TableExport.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate
        
        dotnet pack src/Extensions/Components/BootstrapBlazor.Markdown -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.Markdown.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate
        
        dotnet pack src/Extensions/Components/BootstrapBlazor.FontAwesome -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.FontAwesome.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate
        
        dotnet pack src/Extensions/DataServices/BootstrapBlazor.DataAcces.PetaPoco -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.DataAcces.PetaPoco.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate
        
        dotnet pack src/Extensions/DataServices/BootstrapBlazor.DataAcces.EntityFrameworkCore -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.DataAcces.EntityFrameworkCore.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate
        
        dotnet pack src/Extensions/DataServices/BootstrapBlazor.DataAcces.FreeSql -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.DataAcces.FreeSql.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate
        
        dotnet pack src/Middleware/BootstrapBlazor.Middleware -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.Middleware.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate
