name: Package to Nuget

on:
  push:
    branches:
      - master

jobs:
  pack:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102

    - name: Publish to Nuget
      env: 
        NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}
      run: |      
        dotnet pack src/Extensions/Components/BootstrapBlazor.Chart -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.Chart.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate
        
        dotnet pack src/Extensions/Components/BootstrapBlazor.TableExport -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.TableExport.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate
        
        dotnet pack src/Extensions/Components/BootstrapBlazor.Markdown -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.Markdown.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate
        
        dotnet pack src/Extensions/DataServices/BootstrapBlazor.DataAcces.PetaPoco -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.DataAcces.PetaPoco.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate
        
        dotnet pack src/Extensions/DataServices/BootstrapBlazor.DataAcces.EntityFrameworkCore -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.DataAcces.EntityFrameworkCore.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate
        
        dotnet pack src/Extensions/DataServices/BootstrapBlazor.DataAcces.FreeSql -c Release -o publish
        dotnet nuget push publish/BootstrapBlazor.DataAcces.FreeSql.*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate
